# Generated by Django 4.0.4 on 2022-05-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('lower_age', models.IntegerField()),
                ('upper_age', models.IntegerField()),
                ('poster', models.ImageField(upload_to='MovieImages/')),
            ],
        ),
    ]
