# Generated by Django 4.0.4 on 2022-05-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='C:\\Users\\darsh\\GitHub\\Face-Recognition\\FaceRecognition\\Rec\\MovieImages\\'),
        ),
    ]
