# Generated by Django 4.0.4 on 2022-05-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rec', '0003_alter_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('profile', models.ImageField(upload_to='ProfileImages/')),
            ],
        ),
    ]
